// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TCard: typeof import('tdesign-vue-next')['Card']
    TitlePlaceholder: typeof import('./src/components/header/title-placeholder.vue')['default']
    TSkeleton: typeof import('tdesign-vue-next')['Skeleton']
  }
}
