// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TSkeleton: typeof import('tdesign-vue-next')['Skeleton']
  }
}
