export const FeatureName = {
  Title: "title",
  FullScreen: "full-screen",
  EditMode: "edit-mode",
  Material: "material",
  MaterialDrag: "material-drag",
  ComponentsTree: "components-tree",
  AreaIndicator: "area-indicator",
  SurfaceOperate: "surface-operate",
  ComposeView: "compose-view",
  // RuntimeComponentDrag: "runtime-component-drag",
  RuntimeComponentTree: "runtime-component-tree",
  UndoRedo: "undo-redo",
  EditorRenderType: "editor-render-type",
  GithubHref: "github-href",
};
